### ISSUE TITLE
User moment default language insead of forced English

### ISSUE THREAD

**Issue by dragma** [codebox/moment-precise-range#34] opened 2018-03-16 09:33 UTC
Is there any chance to see this usefull package compatible with moment's locale ?

This is an obviously english-only-package : https://github.com/codebox/moment-precise-range/blob/master/moment-precise-range.js#L6

Atm, i'm using this trick to localise my result, but I find it redundant with the moment's locale

```javascript
moment.frenchPreciseDiff = (toDate, fromDate) => {
  const STRINGS = {
    years: nb => `${nb} an${nb > 1 && 's'}`,
    months: nb => `${nb} mois`,
    days: nb => `${nb} jour${nb > 1 && 's'}`,
    hours: nb => `${nb} heure${nb > 1 && 's'}`,
    minutes: nb => `${nb} mintue${nb > 1 && 's'}`,
    seconds: nb => `${nb} seconde${nb > 1 && 's'}`,
  };
  const data = moment(fromDate).preciseDiff(toDate, true);
  let string = '';
  if (data.years) {
    string = `${string} ${STRINGS.years(data.years)}`;
  }
  if (data.months) {
    string = `${string} ${STRINGS.months(data.months)}`;
  }
  if (data.days) {
    string = `${string} ${STRINGS.days(data.days)}`;
  }
  if (data.hours) {
    string = `${string} ${STRINGS.hours(data.hours)}`;
  }
  if (data.minutes) {
    string = `${string} ${STRINGS.minutes(data.minutes)}`;
  }
  if (data.seconds) {
    string = `${string} ${STRINGS.seconds(data.seconds)}`;
  }
  return string.trim();
};

[...]

const to = moment().add(15, 'd').toDate();
const duration = moment.frenchPreciseDiff(to);
console.log(duration);
```

**Comment by codebox** [comment] 2018-03-16 15:02
Closing because this is a duplicate of https://github.com/codebox/moment-precise-range/issues/6

**Closed as completed by codebox** 2018-03-16 15:02 UTC
