### ISSUE TITLE
require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by sandeshds** [codebox/moment-precise-range#22] opened 2017-04-18 11:00 UTC
Getting this error while importing "moment-precise-range-plugin". 
I believe it is caused due to the following statement 

`if (typeof moment === "undefined" && require) {
    moment = require('moment');
}`

changing it to 
`if (typeof moment === "undefined") {
    moment = require('moment');
}`

fixes the issue. 
Is there a workaround or fix to this ?

**Comment by andfaulkner** [comment] 2017-04-20 12:01
The issue is coming from the very first lines of the module (moment-precise-range.js):

`if (typeof moment === "undefined" && require) {`

The error goes away if we replace it with:

`if (typeof moment === "undefined" && typeof require === 'function') {`

I tried this out locally, and it works perfectly. It also retains the intended purpose of checking for require's existence: to ensure it can be called.

**Comment by codebox** [comment] 2017-04-23 09:04
fixed by @andfaulkner

**Closed by codebox** 2017-04-23 09:04 UTC

**Comment by sandeshds** [comment] 2017-04-24 06:28
I have been using it as an npm package and using the version '1.2.1'. I see that there is no new version that has been published. Are we planning to publish the new version with the fix ?

**Comment by codebox** [comment] 2017-09-14 07:56
npm now at version 1.2.4 which includes latest fixes
